package nr.co.bigmiauu.wega;

import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;

import java.io.OutputStreamWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import android.widget.Toast;
import android.os.Bundle;
import android.app.Activity;
import android.view.Menu;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Handler;

import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.DefaultHttpClient;
import org.apache.http.message.BasicNameValuePair;

import android.app.Activity;
import android.content.pm.ActivityInfo;
import android.os.AsyncTask;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageButton;
import android.widget.Toast;

public class MainActivity extends ActionBarActivity {
    private Button revisab,calificab;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        try {

            OutputStreamWriter fout =
                    new OutputStreamWriter(
                            openFileOutput("profes.txt", MODE_PRIVATE));
            fout.write("Cynthia Leticia Acosta Almodovar\n");
            fout.write("Jose Eduardo Acosta Cano de los Rios\n");
            fout.write("Pedro Rafael Acosta Cano de los Rios\n");
            fout.write("Raul Arturo Acosta Chavez\n");
            fout.write("Benito Aguirre Saenz\n");
            fout.write("Adda Olivia Alanis Araiza\n");
            fout.write("Gerardo Alcantar Burrola\n");
            fout.write("Arturo Alejo Tepate\n");
            fout.write("Manuel Altes Cardenas\n");
            fout.write("Cornelio Alvarez Herrera\n");
            fout.write("Vania Carolina Alvarez Olivas\n");
            fout.write("Rocio Alvidrez Rodriguez\n");
            fout.write("Ramon Anchondo Perez\n");
            fout.write("Maria Antonia Aragon De los Rios\n");
            fout.write("Juan Fernando Arevalo Ruiz\n");
            fout.write("Jorge Alberto Arias Mendoza\n");
            fout.write("Mirna Teresita Armendariz Hernandez\n");
            fout.write("Efren Armendariz Mota\n");
            fout.write("Alejandra Arredondo Mora\n");
            fout.write("Angel Claudio Arzola Mazuca\n");
            fout.write("Fernando Rafael Astorga Bustillos\n");
            fout.write("Gabriela Leticia Avila Orozco\n");
            fout.write("Yolanda Avitia Rodriguez\n");
            fout.write("Vanessa Baeza Olivas\n");
            fout.write("Wilibaldo Barrada Morales\n");
            fout.write("Claudia Barraza Bolivar\n");
            fout.write("Francisco Barraza Jimenez\n");
            fout.write("Miguel Antonio Barreada Contreras\n");
            fout.write("Alfonso Jose Barroso Barajas\n");
            fout.write("Alma Denisse Batista Galvan\n");
            fout.write("Alonso Bautista Villalobos\n");
            fout.write("Oscar Beltran Gomez\n");
            fout.write("Eduardo Enrique Benitez Read\n");
            fout.write("Ricardo Blanco Vega\n");
            fout.write("Karla Bojorquez Gutierrez\n");
            fout.write("Oscar Mauricio Borunda Carrasco\n");
            fout.write("Martha Cecilia Breceda Vargas\n");
            fout.write("Diana Lorelei Bueno Valles\n");
            fout.write("Elizabeth Burrola Marquez\n");
            fout.write("Rosalba Bustillos Villagran\n");
            fout.write("Raymundo Caballero Flores\n");
            fout.write("Marisela Ivette Caldera Franco\n");
            fout.write("Martha Lorena Calderon Fernandez\n");
            fout.write("Alejandro Calderon Landaverde\n");
            fout.write("Alberto Camacho Rios\n");
            fout.write("Victor Luis Camara Aranda\n");
            fout.write("Luis Alfonso Campos Hermosillo\n");
            fout.write("Oscar Cardenas Morales\n");
            fout.write("Claudio Hiram Carmona Jurado\n");
            fout.write("Rene Fernando Carrasco Hernandez\n");
            fout.write("Raul Carrera Resendez\n");
            fout.write("Michelle Carrete Evangelista\n");
            fout.write("Daniela Alejandra Carrillo Treviño\n");
            fout.write("Jose Lino Carrillo Villalobos\n");
            fout.write("Abelardo Casas Comaduran\n");
            fout.write("Jose Castañeda Avila\n");
            fout.write("Rocio Guadalupe Castro Lozoya\n");
            fout.write("Romualdo Chanes Mendoza\n");
            fout.write("Jose Alberto Chaparro Tarango\n");
            fout.write("Jacobo Chavez Gonzalez\n");
            fout.write("Aldo Antonio Cisneros Rodriguez\n");
            fout.write("Manuel Contreras Caraveo\n");
            fout.write("Perla Ivonne Cordero De los Rios\n");
            fout.write("Luis Alberto Corona Reyes\n");
            fout.write("Paola Corona Villa\n");
            fout.write("Mariano Corral Banda\n");
            fout.write("Pedro Enrique Cossio Rodriguez\n");
            fout.write("Mario Andres Cuevas Gutierrez\n");
            fout.write("Rodrigo De la Garza Aguilar\n");
            fout.write("Marco Polo De Leon Palma\n");
            fout.write("Jose Saul De Lira Miramontes\n");
            fout.write("Maria Teresa Delgado Caballero\n");
            fout.write("Afren Armando Delgado Enrique\n");
            fout.write("Guillermo Javier Diaz Greene\n");
            fout.write("Ricardo Zeferino Diaz Morales\n");
            fout.write("Guillermo Diaz Murillo\n");
            fout.write("Raul Reveriano Diaz Quezada\n");
            fout.write("Jesus Miguel Dominguez Dominguez\n");
            fout.write("Alberto Dominguez Quintana\n");
            fout.write("Luis Alonso Dominguez Ramos\n");
            fout.write("Victor Alonso Dominguez Rios\n");
            fout.write("Evaristo Duran Magos\n");
            fout.write("Candy Aurora Duran Ornelas\n");
            fout.write("Luis Gerardo Durstewitz Marta\n");
            fout.write("Alberto Enriquez Bailon\n");
            fout.write("Dalila Jacqueline Escudero Almanza\n");
            fout.write("Jesus Mario Espadas Roque\n");
            fout.write("Alma Rosa Esparza Chavez\n");
            fout.write("Rebeca Minerva Espara Machuca\n");
            fout.write("Nietle Comuna de Paris Esparza Vazquez\n");
            fout.write("Hector Trinidad Espejel Fernandez\n");
            fout.write("Daphne Espejel Garcia\n");
            fout.write("Vanessa Veronica Espejel Garcia\n");
            fout.write("Maria Socorro Espino Valdes\n");
            fout.write("Jose Roberto Espinoza Prieto\n");
            fout.write("Maria Elena Estevane Ortega\n");
            fout.write("Irma Graci Estrada Gutierrez\n");
            fout.write("Juan Carlos Fernandez Chavez\n");
            fout.write("Flores Rogelio Fernandez De Lara\n");
            fout.write("Claudia Annette Fernandez Perez\n");
            fout.write("Luis Carlos Flores Camacho\n");
            fout.write("Juan Pablo Flores De los Rios\n");
            fout.write("Elizabeth Flores Hernandez\n");
            fout.write("Oscar Florez Mendez\n");
            fout.write("Adriana Flores Salcido\n");
            fout.write("Gaston Rene Fourzan Fierro\n");
            fout.write("Miguel Franco Rubio\n");
            fout.write("David Alberto Frescas Chong\n");
            fout.write("Miguel Angel Galaviz Zamarron\n");
            fout.write("Carlos Alfonso Gameros Morales\n");
            fout.write("Margarita Garcia Rivas\n");
            fout.write("Carlos Eduardo Garcia Vargas\n");
            fout.write("Eber Ezequiel Gardea Solis\n");
            fout.write("Hector Alejandro Gomez Corral\n");
            fout.write("Juan Eli Gomez Vidal\n");
            fout.write("Javier Gonzalez Cantu\n");
            fout.write("Luis Carlos Gonzalez Gurrola\n");
            fout.write("Miguel Angel Gonzalez Nuñez\n");
            fout.write("Cesar Gonzalez Valenzuela\n");
            fout.write("Natalia Karina Gonzalez Valenzuela\n");
            fout.write("Jorge Gramer Rivera\n");
            fout.write("Ernesto Guerrero Lestarjette\n");
            fout.write("Blanca Patricia Guerrero Martinez\n");
            fout.write("Addai Guerrero Quiñones\n");
            fout.write("Amalia Irene Guerrero Rodriguez\n");
            fout.write("Carmen Elena Gutierrez Sandoval\n");
            fout.write("Arnoldo Guzman Nieves\n");
            fout.write("Andrei Helo Guereca\n");
            fout.write("Marcela Hernandez Acosta\n");
            fout.write("Elva Socorro Hernandez Hernandez\n");
            fout.write("Hector Hugo Hernandez Hernandez\n");
            fout.write("Gilberto Hernandez Juarez\n");
            fout.write("Alfonso Hernandez Lopez\n");
            fout.write("Fabian Vinicio Hernandez Martinez\n");
            fout.write("Gerardo Arturo Hernandez Talamantes\n");
            fout.write("Jose Luis Herrera Aguilar\n");
            fout.write("Jorge Herrera Gallardo\n");
            fout.write("Eduardo Florencio Herrera Peraza\n");
            fout.write("Nalleli Herrera Pineda\n");
            fout.write("Omar Hinojos Carrasco\n");
            fout.write("Octavio Raul Hinojosa De la Garza\n");
            fout.write("Rafael Holguin Rivas\n");
            fout.write("Rafael Holguin Rivas\n");
            fout.write("Nicolas Holguin Rodriguez\n");
            fout.write("Karina Edith Jimenez Lozano\n");
            fout.write("Raul Alfredo Jimenez Lozano\n");
            fout.write("Mario Alberto Juarez Macias\n");
            fout.write("Karla Ivonne Juarez Magallanes\n");
            fout.write("Arion Ehecatl Juarez Menchaca\n");
            fout.write("Sergio Jurado Medina\n");
            fout.write("Jose Luis Landeros Rivas\n");
            fout.write("Federico Landeros Rodriguez\n");
            fout.write("Ivan Enrique Lara Gonzalez\n");
            fout.write("Carlos Hugo Larrinua Pacheco\n");
            fout.write("Carlos Ignacio Leyva Delgado\n");
            fout.write("Sandra Gabriela Leyva Delgado\n");
            fout.write("Leonardo Agustin Llamas Jimenez\n");
            fout.write("Geronimo Llerar Meza\n");
            fout.write("Hernan Ricardo Lopez De la Riva\n");
            fout.write("Victor Hugo Lopez De Lara Chavez\n");
            fout.write("Marcela Esenia Lopez Ochoa\n");
            fout.write("Claudia Lorena Lopez Olivas\n");
            fout.write("Miguel Angel Lopez Santillan\n");
            fout.write("Aracely Lopez Terrazas\n");
            fout.write("Jesus Humberto Loya Mercado\n");
            fout.write("Roberto Carlos Luna Lozoya\n");
            fout.write("Mario Alberto Madrid Perez\n");
            fout.write("Gregorio Arturo Madrid Ramirez\n");
            fout.write("Fabricio Alan Madrigal Vazquez\n");
            fout.write("Ricardo Majalca Martinez\n");
            fout.write("Magdalena Maldonado Valenzuela\n");
            fout.write("David Maloof Flores\n");
            fout.write("Adolfo Marquez Acosta\n");
            fout.write("Juan Armando Marquez Enriquez\n");
            fout.write("Eloy Normando Marquez Gonzalez\n");
            fout.write("Pedro Rafael Marquez Gutierrez\n");
            fout.write("Leonel Marquez Saenz\n");
            fout.write("Matias Marquez Saenz\n");
            fout.write("Nicolas - Martinez\n");
            fout.write("Cesar Martinez Acosta\n");
            fout.write("Reynaldo Martinez Armenta\n");
            fout.write("Miguel Angel Martinez Lopez\n");
            fout.write("Fernando Martinez Reyes\n");
            fout.write("Javier Maclen Martinez Rodriguez\n");
            fout.write("Javier Alejandro Martinez Rubio\n");
            fout.write("Kristian Martinez Sagredo\n");
            fout.write("Jose Alejandro Martinez Sosa\n");
            fout.write("David Eduardo Medina Guzman\n");
            fout.write("Tanya Lizeth Medina Ronquillo\n");
            fout.write("Luis German Mejia Borja Mendez\n");
            fout.write("Jose Leonel Melchor Ceballos\n");
            fout.write("Pedro Angel Mendez Alvarado\n");
            fout.write("Jorge Mendoza Hernandez\n");
            fout.write("Edgar Eduardo Mendoza Velazquez\n");
            fout.write("Dulce Carolina Minor Avila\n");
            fout.write("Hector Minor Velazquez\n");
            fout.write("Enrique Miranda Flores\n");
            fout.write("Hugo Molina Martinez\n");
            fout.write("Oscar Humberto Monjaras Enriquez\n");
            fout.write("Michel Yadira Montelongo Flores\n");
            fout.write("Jose Carlos Montero De Anda\n");
            fout.write("Luis Carlos Montero Leon\n");
            fout.write("Jose Mora Ruacho\n");
            fout.write("Luis Enrique Morales Gutierrez\n");
            fout.write("Hermes Moreno Alvarez\n");
            fout.write("Alicia Sagrario Moreno Arvizo\n");
            fout.write("Olga Teresa Moriel Acosta\n");
            fout.write("Luis Hebbel Moriel Maldonado\n");
            fout.write("Manuel Antolin Morita Ugarte\n");
            fout.write("Pedro Alberto Muela Molina\n");
            fout.write("Eric Alejandro Muller Garcia\n");
            fout.write("Alejandro Muro Hernandez\n");
            fout.write("Gabriela Muñiz Chavez\n");
            fout.write("Ana Yahaira Muños Gamboa\n");
            fout.write("Jesus Manuel Muñoz Languero\n");
            fout.write("Marisa Isabel Muñoz Ochoa\n");
            fout.write("Claudia Georgina Nava Dino\n");
            fout.write("Carmen Julia Navarro Gomez\n");
            fout.write("Erik Alberto Ochoa Corona\n");
            fout.write("Alan Orlando Ochoa Renteria\n");
            fout.write("Jorge Enrique Ochoa Torres\n");
            fout.write("Marcos Gabriel Ogaz Gonzalez\n");
            fout.write("Cecilia Olivia Olague Caballero\n");
            fout.write("Rosa Imelda Olague Caballero\n");
            fout.write("Hugo Alfredo Olivas Acosta\n");
            fout.write("Alejandra Olivas Davila\n");
            fout.write("Olga Cecilia Olivas Rivera\n");
            fout.write("Mario Alberto Olmos Marquez\n");
            fout.write("Alberto Ornelas Hernandez\n");
            fout.write("Alfredo Ornelas Hernandez\n");
            fout.write("Alicia Ornelas Vargas\n");
            fout.write("Adrian Isaac Orpinel Ureta\n");
            fout.write("Patricia Guadalupe Orpinel Ureta\n");
            fout.write("Ricardo Ortega Diaz\n");
            fout.write("Hermila Ortega Mendoza\n");
            fout.write("Linda Carolina Ortega Robles\n");
            fout.write("Eduardo Ortiz Natividad\n");
            fout.write("Abundio Osuna Vizcarra\n");
            fout.write("Angelica Oviedo Garcia\n");
            fout.write("Rafael Edipo Palma Castillo\n");
            fout.write("Pamela Sisi Paredes Araiza\n");
            fout.write("Sergio Arturo Payan Gomez\n");
            fout.write("Velia Perez Gonzalez\n");
            fout.write("Oscar Daniel Perez Piñon\n");
            fout.write("Gerardo Perez Reveles\n");
            fout.write("Miriam Zulemy Perez Rodallegas\n");
            fout.write("Adan Pinales Munguia\n");
            fout.write("Jesus Roberto Pizarro Chavez\n");
            fout.write("Irma Liz Piñon Carmona\n");
            fout.write("Refugio Antonio Piñon Carmona\n");
            fout.write("Nahim Josafat Ponce Lucero\n");
            fout.write("Jose Antonio Portillo Oceguera\n");
            fout.write("Yessica Prieto Maldonado\n");
            fout.write("Olanda Prieto Ordaz\n");
            fout.write("Alberto Quintana Dominguez\n");
            fout.write("Cristina Idalia Quintana Silveira\n");
            fout.write("Erick Octavio Quiones Rodriguez\n");
            fout.write("Luis Carlos Quiñones Baca\n");
            fout.write("Edna Guadalupe Radovich Perez\n");
            fout.write("Francisco Ramirez Kohler\n");
            fout.write("Rocio Alejandra Ramirez Lira\n");
            fout.write("Luis Antonio Ramirez Martinez\n");
            fout.write("Gabriela Rascon Soto\n");
            fout.write("Julia Liliana Requeña Yañez\n");
            fout.write("Ignacio Alfonso Reyes Cortes\n");
            fout.write("Carmen Rosalia Reyes Reyna\n");
            fout.write("Manuel de Jesus Rincon Camacho\n");
            fout.write("Abril Cecilia Rios Lopez\n");
            fout.write("Aurora Robledo Ruiz\n");
            fout.write("Valentin Federico Rodriguez Alvarado\n");
            fout.write("Ricardo Alberto Rodriguez Fonseca\n");
            fout.write("Amparo Margarita Rodriguez Gallegos\n");
            fout.write("Carlos Fransisco Rodriguez Guevara\n");
            fout.write("Beatriz Adriana Rodriguez Varela\n");
            fout.write("Hector David Romero Granados\n");
            fout.write("Jorge Armando Rubio Perea\n");
            fout.write("Adriana Ruiz Anchondo\n");
            fout.write("Hector David Ruiz Cisneros\n");
            fout.write("Yesica Olivia Ruiz Holguin\n");
            fout.write("Jorge Iden Ruiz Quintana\n");
            fout.write("Maria Selene Ruiz Rivero\n");
            fout.write("Rodrigo Ruiz Santos\n");
            fout.write("Oscar Ramses Ruiz Varela\n");
            fout.write("Alfonso Saens Marquez\n");
            fout.write("Jesus Saenz Olivas\n");
            fout.write("Victor Alfonso Salas Aguilar\n");
            fout.write("Lizbeth Salas Lechuga\n");
            fout.write("Luis Alfonso Salcido Hernandez\n");
            fout.write("Saul Alejandro Salomon Jaramillo\n");
            fout.write("Hugo Alejandro San Martin Benavides\n");
            fout.write("Marco Antonio Sanchez Vazquez\n");
            fout.write("Raul Sandoval Jabalera\n");
            fout.write("Laura Veronica Sandoval Romero\n");
            fout.write("Ivonne Aracely Santillan Martinez\n");
            fout.write("Jose Santos Garcia\n");
            fout.write("Daniel Sayto Corona\n");
            fout.write("David Armando Sias Casas\n");
            fout.write("Leonardo Sias Elizondo\n");
            fout.write("Humberto Silva Hidalgo\n");
            fout.write("Claudia Maria Sinaloa Rodriguez\n");
            fout.write("Sergio Solis Castillo\n");
            fout.write("Gilberto Sosa Najera\n");
            fout.write("Erick Ivan Teran Corral\n");
            fout.write("Carlos Alberto Terrazs Venegas\n");
            fout.write("Agustin Javier Tonche Ramos\n");
            fout.write("Daniel Oviel Torres Cisneros\n");
            fout.write("Aaron Torres Orozco\n");
            fout.write("Joaquin Gilberto Treviño Davila\n");
            fout.write("Edgar Trujillo Preciado\n");
            fout.write("Gerardo Trujillo Schiaffino\n");
            fout.write("Maria Ugarte De la Rosa\n");
            fout.write("Wenceslado Melecio Urbina Chavez\n");
            fout.write("Adolfo Valdes Chavez\n");
            fout.write("Carlos Valdez Fragoso\n");
            fout.write("Julio Cesar Valdez Muñoz\n");
            fout.write("Erick Saul Varela Hernandez\n");
            fout.write("Beatriz Vazquez Gonzalez\n");
            fout.write("Maria Isabel Vazquez Gonzalez\n");
            fout.write("Mayra Elena Vega Carrasco\n");
            fout.write("LizzetVelazquez Vega Portillo\n");
            fout.write("Maria Alejandra Velazquez Cazares\n");
            fout.write("Roberto Velazquez Talamantes\n");
            fout.write("Jose Elias Villa Herrera\n");
            fout.write("Marisol Villa Herrera\n");
            fout.write("Maria de Lourdes - Villalba\n");
            fout.write("Alejandro Villalobos Aragon\n");
            fout.close();





        } catch (Exception ex) {

        }


    }



    public void revisa(View view) {

        String[] archivos = fileList();
        if(!existe(archivos, "profes.txt")) {
            try {

                OutputStreamWriter fout =
                        new OutputStreamWriter(
                                openFileOutput("profes.txt", MODE_PRIVATE));
                fout.write("Cynthia Leticia Acosta Almodovar\n");
                fout.write("Jose Eduardo Acosta Cano de los Rios\n");
                fout.write("Pedro Rafael Acosta Cano de los Rios\n");
                fout.write("Raul Arturo Acosta Chavez\n");
                fout.write("Benito Aguirre Saenz\n");
                fout.write("Adda Olivia Alanis Araiza\n");
                fout.write("Gerardo Alcantar Burrola\n");
                fout.write("Arturo Alejo Tepate\n");
                fout.write("Manuel Altes Cardenas\n");
                fout.write("Cornelio Alvarez Herrera\n");
                fout.write("Vania Carolina Alvarez Olivas\n");
                fout.write("Rocio Alvidrez Rodriguez\n");
                fout.write("Ramon Anchondo Perez\n");
                fout.write("Maria Antonia Aragon De los Rios\n");
                fout.write("Juan Fernando Arevalo Ruiz\n");
                fout.write("Jorge Alberto Arias Mendoza\n");
                fout.write("Mirna Teresita Armendariz Hernandez\n");
                fout.write("Efren Armendariz Mota\n");
                fout.write("Alejandra Arredondo Mora\n");
                fout.write("Angel Claudio Arzola Mazuca\n");
                fout.write("Fernando Rafael Astorga Bustillos\n");
                fout.write("Gabriela Leticia Avila Orozco\n");
                fout.write("Yolanda Avitia Rodriguez\n");
                fout.write("Vanessa Baeza Olivas\n");
                fout.write("Wilibaldo Barrada Morales\n");
                fout.write("Claudia Barraza Bolivar\n");
                fout.write("Francisco Barraza Jimenez\n");
                fout.write("Miguel Antonio Barreada Contreras\n");
                fout.write("Alfonso Jose Barroso Barajas\n");
                fout.write("Alma Denisse Batista Galvan\n");
                fout.write("Alonso Bautista Villalobos\n");
                fout.write("Oscar Beltran Gomez\n");
                fout.write("Eduardo Enrique Benitez Read\n");
                fout.write("Ricardo Blanco Vega\n");
                fout.write("Karla Bojorquez Gutierrez\n");
                fout.write("Oscar Mauricio Borunda Carrasco\n");
                fout.write("Martha Cecilia Breceda Vargas\n");
                fout.write("Diana Lorelei Bueno Valles\n");
                fout.write("Elizabeth Burrola Marquez\n");
                fout.write("Rosalba Bustillos Villagran\n");
                fout.write("Raymundo Caballero Flores\n");
                fout.write("Marisela Ivette Caldera Franco\n");
                fout.write("Martha Lorena Calderon Fernandez\n");
                fout.write("Alejandro Calderon Landaverde\n");
                fout.write("Alberto Camacho Rios\n");
                fout.write("Victor Luis Camara Aranda\n");
                fout.write("Luis Alfonso Campos Hermosillo\n");
                fout.write("Oscar Cardenas Morales\n");
                fout.write("Claudio Hiram Carmona Jurado\n");
                fout.write("Rene Fernando Carrasco Hernandez\n");
                fout.write("Raul Carrera Resendez\n");
                fout.write("Michelle Carrete Evangelista\n");
                fout.write("Daniela Alejandra Carrillo Treviño\n");
                fout.write("Jose Lino Carrillo Villalobos\n");
                fout.write("Abelardo Casas Comaduran\n");
                fout.write("Jose Castañeda Avila\n");
                fout.write("Rocio Guadalupe Castro Lozoya\n");
                fout.write("Romualdo Chanes Mendoza\n");
                fout.write("Jose Alberto Chaparro Tarango\n");
                fout.write("Jacobo Chavez Gonzalez\n");
                fout.write("Aldo Antonio Cisneros Rodriguez\n");
                fout.write("Manuel Contreras Caraveo\n");
                fout.write("Perla Ivonne Cordero De los Rios\n");
                fout.write("Luis Alberto Corona Reyes\n");
                fout.write("Paola Corona Villa\n");
                fout.write("Mariano Corral Banda\n");
                fout.write("Pedro Enrique Cossio Rodriguez\n");
                fout.write("Mario Andres Cuevas Gutierrez\n");
                fout.write("Rodrigo De la Garza Aguilar\n");
                fout.write("Marco Polo De Leon Palma\n");
                fout.write("Jose Saul De Lira Miramontes\n");
                fout.write("Maria Teresa Delgado Caballero\n");
                fout.write("Afren Armando Delgado Enrique\n");
                fout.write("Guillermo Javier Diaz Greene\n");
                fout.write("Ricardo Zeferino Diaz Morales\n");
                fout.write("Guillermo Diaz Murillo\n");
                fout.write("Raul Reveriano Diaz Quezada\n");
                fout.write("Jesus Miguel Dominguez Dominguez\n");
                fout.write("Alberto Dominguez Quintana\n");
                fout.write("Luis Alonso Dominguez Ramos\n");
                fout.write("Victor Alonso Dominguez Rios\n");
                fout.write("Evaristo Duran Magos\n");
                fout.write("Candy Aurora Duran Ornelas\n");
                fout.write("Luis Gerardo Durstewitz Marta\n");
                fout.write("Alberto Enriquez Bailon\n");
                fout.write("Dalila Jacqueline Escudero Almanza\n");
                fout.write("Jesus Mario Espadas Roque\n");
                fout.write("Alma Rosa Esparza Chavez\n");
                fout.write("Rebeca Minerva Espara Machuca\n");
                fout.write("Nietle Comuna de Paris Esparza Vazquez\n");
                fout.write("Hector Trinidad Espejel Fernandez\n");
                fout.write("Daphne Espejel Garcia\n");
                fout.write("Vanessa Veronica Espejel Garcia\n");
                fout.write("Maria Socorro Espino Valdes\n");
                fout.write("Jose Roberto Espinoza Prieto\n");
                fout.write("Maria Elena Estevane Ortega\n");
                fout.write("Irma Graci Estrada Gutierrez\n");
                fout.write("Juan Carlos Fernandez Chavez\n");
                fout.write("Flores Rogelio Fernandez De Lara\n");
                fout.write("Claudia Annette Fernandez Perez\n");
                fout.write("Luis Carlos Flores Camacho\n");
                fout.write("Juan Pablo Flores De los Rios\n");
                fout.write("Elizabeth Flores Hernandez\n");
                fout.write("Oscar Florez Mendez\n");
                fout.write("Adriana Flores Salcido\n");
                fout.write("Gaston Rene Fourzan Fierro\n");
                fout.write("Miguel Franco Rubio\n");
                fout.write("David Alberto Frescas Chong\n");
                fout.write("Miguel Angel Galaviz Zamarron\n");
                fout.write("Carlos Alfonso Gameros Morales\n");
                fout.write("Margarita Garcia Rivas\n");
                fout.write("Carlos Eduardo Garcia Vargas\n");
                fout.write("Eber Ezequiel Gardea Solis\n");
                fout.write("Hector Alejandro Gomez Corral\n");
                fout.write("Juan Eli Gomez Vidal\n");
                fout.write("Javier Gonzalez Cantu\n");
                fout.write("Luis Carlos Gonzalez Gurrola\n");
                fout.write("Miguel Angel Gonzalez Nuñez\n");
                fout.write("Cesar Gonzalez Valenzuela\n");
                fout.write("Natalia Karina Gonzalez Valenzuela\n");
                fout.write("Jorge Gramer Rivera\n");
                fout.write("Ernesto Guerrero Lestarjette\n");
                fout.write("Blanca Patricia Guerrero Martinez\n");
                fout.write("Addai Guerrero Quiñones\n");
                fout.write("Amalia Irene Guerrero Rodriguez\n");
                fout.write("Carmen Elena Gutierrez Sandoval\n");
                fout.write("Arnoldo Guzman Nieves\n");
                fout.write("Andrei Helo Guereca\n");
                fout.write("Marcela Hernandez Acosta\n");
                fout.write("Elva Socorro Hernandez Hernandez\n");
                fout.write("Hector Hugo Hernandez Hernandez\n");
                fout.write("Gilberto Hernandez Juarez\n");
                fout.write("Alfonso Hernandez Lopez\n");
                fout.write("Fabian Vinicio Hernandez Martinez\n");
                fout.write("Gerardo Arturo Hernandez Talamantes\n");
                fout.write("Jose Luis Herrera Aguilar\n");
                fout.write("Jorge Herrera Gallardo\n");
                fout.write("Eduardo Florencio Herrera Peraza\n");
                fout.write("Nalleli Herrera Pineda\n");
                fout.write("Omar Hinojos Carrasco\n");
                fout.write("Octavio Raul Hinojosa De la Garza\n");
                fout.write("Rafael Holguin Rivas\n");
                fout.write("Rafael Holguin Rivas\n");
                fout.write("Nicolas Holguin Rodriguez\n");
                fout.write("Karina Edith Jimenez Lozano\n");
                fout.write("Raul Alfredo Jimenez Lozano\n");
                fout.write("Mario Alberto Juarez Macias\n");
                fout.write("Karla Ivonne Juarez Magallanes\n");
                fout.write("Arion Ehecatl Juarez Menchaca\n");
                fout.write("Sergio Jurado Medina\n");
                fout.write("Jose Luis Landeros Rivas\n");
                fout.write("Federico Landeros Rodriguez\n");
                fout.write("Ivan Enrique Lara Gonzalez\n");
                fout.write("Carlos Hugo Larrinua Pacheco\n");
                fout.write("Carlos Ignacio Leyva Delgado\n");
                fout.write("Sandra Gabriela Leyva Delgado\n");
                fout.write("Leonardo Agustin Llamas Jimenez\n");
                fout.write("Geronimo Llerar Meza\n");
                fout.write("Hernan Ricardo Lopez De la Riva\n");
                fout.write("Victor Hugo Lopez De Lara Chavez\n");
                fout.write("Marcela Esenia Lopez Ochoa\n");
                fout.write("Claudia Lorena Lopez Olivas\n");
                fout.write("Miguel Angel Lopez Santillan\n");
                fout.write("Aracely Lopez Terrazas\n");
                fout.write("Jesus Humberto Loya Mercado\n");
                fout.write("Roberto Carlos Luna Lozoya\n");
                fout.write("Mario Alberto Madrid Perez\n");
                fout.write("Gregorio Arturo Madrid Ramirez\n");
                fout.write("Fabricio Alan Madrigal Vazquez\n");
                fout.write("Ricardo Majalca Martinez\n");
                fout.write("Magdalena Maldonado Valenzuela\n");
                fout.write("David Maloof Flores\n");
                fout.write("Adolfo Marquez Acosta\n");
                fout.write("Juan Armando Marquez Enriquez\n");
                fout.write("Eloy Normando Marquez Gonzalez\n");
                fout.write("Pedro Rafael Marquez Gutierrez\n");
                fout.write("Leonel Marquez Saenz\n");
                fout.write("Matias Marquez Saenz\n");
                fout.write("Nicolas - Martinez\n");
                fout.write("Cesar Martinez Acosta\n");
                fout.write("Reynaldo Martinez Armenta\n");
                fout.write("Miguel Angel Martinez Lopez\n");
                fout.write("Fernando Martinez Reyes\n");
                fout.write("Javier Maclen Martinez Rodriguez\n");
                fout.write("Javier Alejandro Martinez Rubio\n");
                fout.write("Kristian Martinez Sagredo\n");
                fout.write("Jose Alejandro Martinez Sosa\n");
                fout.write("David Eduardo Medina Guzman\n");
                fout.write("Tanya Lizeth Medina Ronquillo\n");
                fout.write("Luis German Mejia Borja Mendez\n");
                fout.write("Jose Leonel Melchor Ceballos\n");
                fout.write("Pedro Angel Mendez Alvarado\n");
                fout.write("Jorge Mendoza Hernandez\n");
                fout.write("Edgar Eduardo Mendoza Velazquez\n");
                fout.write("Dulce Carolina Minor Avila\n");
                fout.write("Hector Minor Velazquez\n");
                fout.write("Enrique Miranda Flores\n");
                fout.write("Hugo Molina Martinez\n");
                fout.write("Oscar Humberto Monjaras Enriquez\n");
                fout.write("Michel Yadira Montelongo Flores\n");
                fout.write("Jose Carlos Montero De Anda\n");
                fout.write("Luis Carlos Montero Leon\n");
                fout.write("Jose Mora Ruacho\n");
                fout.write("Luis Enrique Morales Gutierrez\n");
                fout.write("Hermes Moreno Alvarez\n");
                fout.write("Alicia Sagrario Moreno Arvizo\n");
                fout.write("Olga Teresa Moriel Acosta\n");
                fout.write("Luis Hebbel Moriel Maldonado\n");
                fout.write("Manuel Antolin Morita Ugarte\n");
                fout.write("Pedro Alberto Muela Molina\n");
                fout.write("Eric Alejandro Muller Garcia\n");
                fout.write("Alejandro Muro Hernandez\n");
                fout.write("Gabriela Muñiz Chavez\n");
                fout.write("Ana Yahaira Muños Gamboa\n");
                fout.write("Jesus Manuel Muñoz Languero\n");
                fout.write("Marisa Isabel Muñoz Ochoa\n");
                fout.write("Claudia Georgina Nava Dino\n");
                fout.write("Carmen Julia Navarro Gomez\n");
                fout.write("Erik Alberto Ochoa Corona\n");
                fout.write("Alan Orlando Ochoa Renteria\n");
                fout.write("Jorge Enrique Ochoa Torres\n");
                fout.write("Marcos Gabriel Ogaz Gonzalez\n");
                fout.write("Cecilia Olivia Olague Caballero\n");
                fout.write("Rosa Imelda Olague Caballero\n");
                fout.write("Hugo Alfredo Olivas Acosta\n");
                fout.write("Alejandra Olivas Davila\n");
                fout.write("Olga Cecilia Olivas Rivera\n");
                fout.write("Mario Alberto Olmos Marquez\n");
                fout.write("Alberto Ornelas Hernandez\n");
                fout.write("Alfredo Ornelas Hernandez\n");
                fout.write("Alicia Ornelas Vargas\n");
                fout.write("Adrian Isaac Orpinel Ureta\n");
                fout.write("Patricia Guadalupe Orpinel Ureta\n");
                fout.write("Ricardo Ortega Diaz\n");
                fout.write("Hermila Ortega Mendoza\n");
                fout.write("Linda Carolina Ortega Robles\n");
                fout.write("Eduardo Ortiz Natividad\n");
                fout.write("Abundio Osuna Vizcarra\n");
                fout.write("Angelica Oviedo Garcia\n");
                fout.write("Rafael Edipo Palma Castillo\n");
                fout.write("Pamela Sisi Paredes Araiza\n");
                fout.write("Sergio Arturo Payan Gomez\n");
                fout.write("Velia Perez Gonzalez\n");
                fout.write("Oscar Daniel Perez Piñon\n");
                fout.write("Gerardo Perez Reveles\n");
                fout.write("Miriam Zulemy Perez Rodallegas\n");
                fout.write("Adan Pinales Munguia\n");
                fout.write("Jesus Roberto Pizarro Chavez\n");
                fout.write("Irma Liz Piñon Carmona\n");
                fout.write("Refugio Antonio Piñon Carmona\n");
                fout.write("Nahim Josafat Ponce Lucero\n");
                fout.write("Jose Antonio Portillo Oceguera\n");
                fout.write("Yessica Prieto Maldonado\n");
                fout.write("Olanda Prieto Ordaz\n");
                fout.write("Alberto Quintana Dominguez\n");
                fout.write("Cristina Idalia Quintana Silveira\n");
                fout.write("Erick Octavio Quiones Rodriguez\n");
                fout.write("Luis Carlos Quiñones Baca\n");
                fout.write("Edna Guadalupe Radovich Perez\n");
                fout.write("Francisco Ramirez Kohler\n");
                fout.write("Rocio Alejandra Ramirez Lira\n");
                fout.write("Luis Antonio Ramirez Martinez\n");
                fout.write("Gabriela Rascon Soto\n");
                fout.write("Julia Liliana Requeña Yañez\n");
                fout.write("Ignacio Alfonso Reyes Cortes\n");
                fout.write("Carmen Rosalia Reyes Reyna\n");
                fout.write("Manuel de Jesus Rincon Camacho\n");
                fout.write("Abril Cecilia Rios Lopez\n");
                fout.write("Aurora Robledo Ruiz\n");
                fout.write("Valentin Federico Rodriguez Alvarado\n");
                fout.write("Ricardo Alberto Rodriguez Fonseca\n");
                fout.write("Amparo Margarita Rodriguez Gallegos\n");
                fout.write("Carlos Fransisco Rodriguez Guevara\n");
                fout.write("Beatriz Adriana Rodriguez Varela\n");
                fout.write("Hector David Romero Granados\n");
                fout.write("Jorge Armando Rubio Perea\n");
                fout.write("Adriana Ruiz Anchondo\n");
                fout.write("Hector David Ruiz Cisneros\n");
                fout.write("Yesica Olivia Ruiz Holguin\n");
                fout.write("Jorge Iden Ruiz Quintana\n");
                fout.write("Maria Selene Ruiz Rivero\n");
                fout.write("Rodrigo Ruiz Santos\n");
                fout.write("Oscar Ramses Ruiz Varela\n");
                fout.write("Alfonso Saens Marquez\n");
                fout.write("Jesus Saenz Olivas\n");
                fout.write("Victor Alfonso Salas Aguilar\n");
                fout.write("Lizbeth Salas Lechuga\n");
                fout.write("Luis Alfonso Salcido Hernandez\n");
                fout.write("Saul Alejandro Salomon Jaramillo\n");
                fout.write("Hugo Alejandro San Martin Benavides\n");
                fout.write("Marco Antonio Sanchez Vazquez\n");
                fout.write("Raul Sandoval Jabalera\n");
                fout.write("Laura Veronica Sandoval Romero\n");
                fout.write("Ivonne Aracely Santillan Martinez\n");
                fout.write("Jose Santos Garcia\n");
                fout.write("Daniel Sayto Corona\n");
                fout.write("David Armando Sias Casas\n");
                fout.write("Leonardo Sias Elizondo\n");
                fout.write("Humberto Silva Hidalgo\n");
                fout.write("Claudia Maria Sinaloa Rodriguez\n");
                fout.write("Sergio Solis Castillo\n");
                fout.write("Gilberto Sosa Najera\n");
                fout.write("Erick Ivan Teran Corral\n");
                fout.write("Carlos Alberto Terrazs Venegas\n");
                fout.write("Agustin Javier Tonche Ramos\n");
                fout.write("Daniel Oviel Torres Cisneros\n");
                fout.write("Aaron Torres Orozco\n");
                fout.write("Joaquin Gilberto Treviño Davila\n");
                fout.write("Edgar Trujillo Preciado\n");
                fout.write("Gerardo Trujillo Schiaffino\n");
                fout.write("Maria Ugarte De la Rosa\n");
                fout.write("Wenceslado Melecio Urbina Chavez\n");
                fout.write("Adolfo Valdes Chavez\n");
                fout.write("Carlos Valdez Fragoso\n");
                fout.write("Julio Cesar Valdez Muñoz\n");
                fout.write("Erick Saul Varela Hernandez\n");
                fout.write("Beatriz Vazquez Gonzalez\n");
                fout.write("Maria Isabel Vazquez Gonzalez\n");
                fout.write("Mayra Elena Vega Carrasco\n");
                fout.write("LizzetVelazquez Vega Portillo\n");
                fout.write("Maria Alejandra Velazquez Cazares\n");
                fout.write("Roberto Velazquez Talamantes\n");
                fout.write("Jose Elias Villa Herrera\n");
                fout.write("Marisol Villa Herrera\n");
                fout.write("Maria de Lourdes - Villalba\n");
                fout.write("Alejandro Villalobos Aragon\n");
                fout.close();





            } catch (Exception ex) {

            }
        }
        Intent j = new Intent(this, MainActivity4.class );
        startActivity(j);
    }

    public void califica(View view) {


        String[] archivos = fileList();
        if(!existe(archivos, "profes.txt")) {
            try {

                OutputStreamWriter fout =
                        new OutputStreamWriter(
                                openFileOutput("profes.txt", MODE_PRIVATE));
                fout.write("Cynthia Leticia Acosta Almodovar\n");
                fout.write("Jose Eduardo Acosta Cano de los Rios\n");
                fout.write("Pedro Rafael Acosta Cano de los Rios\n");
                fout.write("Raul Arturo Acosta Chavez\n");
                fout.write("Benito Aguirre Saenz\n");
                fout.write("Adda Olivia Alanis Araiza\n");
                fout.write("Gerardo Alcantar Burrola\n");
                fout.write("Arturo Alejo Tepate\n");
                fout.write("Manuel Altes Cardenas\n");
                fout.write("Cornelio Alvarez Herrera\n");
                fout.write("Vania Carolina Alvarez Olivas\n");
                fout.write("Rocio Alvidrez Rodriguez\n");
                fout.write("Ramon Anchondo Perez\n");
                fout.write("Maria Antonia Aragon De los Rios\n");
                fout.write("Juan Fernando Arevalo Ruiz\n");
                fout.write("Jorge Alberto Arias Mendoza\n");
                fout.write("Mirna Teresita Armendariz Hernandez\n");
                fout.write("Efren Armendariz Mota\n");
                fout.write("Alejandra Arredondo Mora\n");
                fout.write("Angel Claudio Arzola Mazuca\n");
                fout.write("Fernando Rafael Astorga Bustillos\n");
                fout.write("Gabriela Leticia Avila Orozco\n");
                fout.write("Yolanda Avitia Rodriguez\n");
                fout.write("Vanessa Baeza Olivas\n");
                fout.write("Wilibaldo Barrada Morales\n");
                fout.write("Claudia Barraza Bolivar\n");
                fout.write("Francisco Barraza Jimenez\n");
                fout.write("Miguel Antonio Barreada Contreras\n");
                fout.write("Alfonso Jose Barroso Barajas\n");
                fout.write("Alma Denisse Batista Galvan\n");
                fout.write("Alonso Bautista Villalobos\n");
                fout.write("Oscar Beltran Gomez\n");
                fout.write("Eduardo Enrique Benitez Read\n");
                fout.write("Ricardo Blanco Vega\n");
                fout.write("Karla Bojorquez Gutierrez\n");
                fout.write("Oscar Mauricio Borunda Carrasco\n");
                fout.write("Martha Cecilia Breceda Vargas\n");
                fout.write("Diana Lorelei Bueno Valles\n");
                fout.write("Elizabeth Burrola Marquez\n");
                fout.write("Rosalba Bustillos Villagran\n");
                fout.write("Raymundo Caballero Flores\n");
                fout.write("Marisela Ivette Caldera Franco\n");
                fout.write("Martha Lorena Calderon Fernandez\n");
                fout.write("Alejandro Calderon Landaverde\n");
                fout.write("Alberto Camacho Rios\n");
                fout.write("Victor Luis Camara Aranda\n");
                fout.write("Luis Alfonso Campos Hermosillo\n");
                fout.write("Oscar Cardenas Morales\n");
                fout.write("Claudio Hiram Carmona Jurado\n");
                fout.write("Rene Fernando Carrasco Hernandez\n");
                fout.write("Raul Carrera Resendez\n");
                fout.write("Michelle Carrete Evangelista\n");
                fout.write("Daniela Alejandra Carrillo Treviño\n");
                fout.write("Jose Lino Carrillo Villalobos\n");
                fout.write("Abelardo Casas Comaduran\n");
                fout.write("Jose Castañeda Avila\n");
                fout.write("Rocio Guadalupe Castro Lozoya\n");
                fout.write("Romualdo Chanes Mendoza\n");
                fout.write("Jose Alberto Chaparro Tarango\n");
                fout.write("Jacobo Chavez Gonzalez\n");
                fout.write("Aldo Antonio Cisneros Rodriguez\n");
                fout.write("Manuel Contreras Caraveo\n");
                fout.write("Perla Ivonne Cordero De los Rios\n");
                fout.write("Luis Alberto Corona Reyes\n");
                fout.write("Paola Corona Villa\n");
                fout.write("Mariano Corral Banda\n");
                fout.write("Pedro Enrique Cossio Rodriguez\n");
                fout.write("Mario Andres Cuevas Gutierrez\n");
                fout.write("Rodrigo De la Garza Aguilar\n");
                fout.write("Marco Polo De Leon Palma\n");
                fout.write("Jose Saul De Lira Miramontes\n");
                fout.write("Maria Teresa Delgado Caballero\n");
                fout.write("Afren Armando Delgado Enrique\n");
                fout.write("Guillermo Javier Diaz Greene\n");
                fout.write("Ricardo Zeferino Diaz Morales\n");
                fout.write("Guillermo Diaz Murillo\n");
                fout.write("Raul Reveriano Diaz Quezada\n");
                fout.write("Jesus Miguel Dominguez Dominguez\n");
                fout.write("Alberto Dominguez Quintana\n");
                fout.write("Luis Alonso Dominguez Ramos\n");
                fout.write("Victor Alonso Dominguez Rios\n");
                fout.write("Evaristo Duran Magos\n");
                fout.write("Candy Aurora Duran Ornelas\n");
                fout.write("Luis Gerardo Durstewitz Marta\n");
                fout.write("Alberto Enriquez Bailon\n");
                fout.write("Dalila Jacqueline Escudero Almanza\n");
                fout.write("Jesus Mario Espadas Roque\n");
                fout.write("Alma Rosa Esparza Chavez\n");
                fout.write("Rebeca Minerva Espara Machuca\n");
                fout.write("Nietle Comuna de Paris Esparza Vazquez\n");
                fout.write("Hector Trinidad Espejel Fernandez\n");
                fout.write("Daphne Espejel Garcia\n");
                fout.write("Vanessa Veronica Espejel Garcia\n");
                fout.write("Maria Socorro Espino Valdes\n");
                fout.write("Jose Roberto Espinoza Prieto\n");
                fout.write("Maria Elena Estevane Ortega\n");
                fout.write("Irma Graci Estrada Gutierrez\n");
                fout.write("Juan Carlos Fernandez Chavez\n");
                fout.write("Flores Rogelio Fernandez De Lara\n");
                fout.write("Claudia Annette Fernandez Perez\n");
                fout.write("Luis Carlos Flores Camacho\n");
                fout.write("Juan Pablo Flores De los Rios\n");
                fout.write("Elizabeth Flores Hernandez\n");
                fout.write("Oscar Florez Mendez\n");
                fout.write("Adriana Flores Salcido\n");
                fout.write("Gaston Rene Fourzan Fierro\n");
                fout.write("Miguel Franco Rubio\n");
                fout.write("David Alberto Frescas Chong\n");
                fout.write("Miguel Angel Galaviz Zamarron\n");
                fout.write("Carlos Alfonso Gameros Morales\n");
                fout.write("Margarita Garcia Rivas\n");
                fout.write("Carlos Eduardo Garcia Vargas\n");
                fout.write("Eber Ezequiel Gardea Solis\n");
                fout.write("Hector Alejandro Gomez Corral\n");
                fout.write("Juan Eli Gomez Vidal\n");
                fout.write("Javier Gonzalez Cantu\n");
                fout.write("Luis Carlos Gonzalez Gurrola\n");
                fout.write("Miguel Angel Gonzalez Nuñez\n");
                fout.write("Cesar Gonzalez Valenzuela\n");
                fout.write("Natalia Karina Gonzalez Valenzuela\n");
                fout.write("Jorge Gramer Rivera\n");
                fout.write("Ernesto Guerrero Lestarjette\n");
                fout.write("Blanca Patricia Guerrero Martinez\n");
                fout.write("Addai Guerrero Quiñones\n");
                fout.write("Amalia Irene Guerrero Rodriguez\n");
                fout.write("Carmen Elena Gutierrez Sandoval\n");
                fout.write("Arnoldo Guzman Nieves\n");
                fout.write("Andrei Helo Guereca\n");
                fout.write("Marcela Hernandez Acosta\n");
                fout.write("Elva Socorro Hernandez Hernandez\n");
                fout.write("Hector Hugo Hernandez Hernandez\n");
                fout.write("Gilberto Hernandez Juarez\n");
                fout.write("Alfonso Hernandez Lopez\n");
                fout.write("Fabian Vinicio Hernandez Martinez\n");
                fout.write("Gerardo Arturo Hernandez Talamantes\n");
                fout.write("Jose Luis Herrera Aguilar\n");
                fout.write("Jorge Herrera Gallardo\n");
                fout.write("Eduardo Florencio Herrera Peraza\n");
                fout.write("Nalleli Herrera Pineda\n");
                fout.write("Omar Hinojos Carrasco\n");
                fout.write("Octavio Raul Hinojosa De la Garza\n");
                fout.write("Rafael Holguin Rivas\n");
                fout.write("Rafael Holguin Rivas\n");
                fout.write("Nicolas Holguin Rodriguez\n");
                fout.write("Karina Edith Jimenez Lozano\n");
                fout.write("Raul Alfredo Jimenez Lozano\n");
                fout.write("Mario Alberto Juarez Macias\n");
                fout.write("Karla Ivonne Juarez Magallanes\n");
                fout.write("Arion Ehecatl Juarez Menchaca\n");
                fout.write("Sergio Jurado Medina\n");
                fout.write("Jose Luis Landeros Rivas\n");
                fout.write("Federico Landeros Rodriguez\n");
                fout.write("Ivan Enrique Lara Gonzalez\n");
                fout.write("Carlos Hugo Larrinua Pacheco\n");
                fout.write("Carlos Ignacio Leyva Delgado\n");
                fout.write("Sandra Gabriela Leyva Delgado\n");
                fout.write("Leonardo Agustin Llamas Jimenez\n");
                fout.write("Geronimo Llerar Meza\n");
                fout.write("Hernan Ricardo Lopez De la Riva\n");
                fout.write("Victor Hugo Lopez De Lara Chavez\n");
                fout.write("Marcela Esenia Lopez Ochoa\n");
                fout.write("Claudia Lorena Lopez Olivas\n");
                fout.write("Miguel Angel Lopez Santillan\n");
                fout.write("Aracely Lopez Terrazas\n");
                fout.write("Jesus Humberto Loya Mercado\n");
                fout.write("Roberto Carlos Luna Lozoya\n");
                fout.write("Mario Alberto Madrid Perez\n");
                fout.write("Gregorio Arturo Madrid Ramirez\n");
                fout.write("Fabricio Alan Madrigal Vazquez\n");
                fout.write("Ricardo Majalca Martinez\n");
                fout.write("Magdalena Maldonado Valenzuela\n");
                fout.write("David Maloof Flores\n");
                fout.write("Adolfo Marquez Acosta\n");
                fout.write("Juan Armando Marquez Enriquez\n");
                fout.write("Eloy Normando Marquez Gonzalez\n");
                fout.write("Pedro Rafael Marquez Gutierrez\n");
                fout.write("Leonel Marquez Saenz\n");
                fout.write("Matias Marquez Saenz\n");
                fout.write("Nicolas - Martinez\n");
                fout.write("Cesar Martinez Acosta\n");
                fout.write("Reynaldo Martinez Armenta\n");
                fout.write("Miguel Angel Martinez Lopez\n");
                fout.write("Fernando Martinez Reyes\n");
                fout.write("Javier Maclen Martinez Rodriguez\n");
                fout.write("Javier Alejandro Martinez Rubio\n");
                fout.write("Kristian Martinez Sagredo\n");
                fout.write("Jose Alejandro Martinez Sosa\n");
                fout.write("David Eduardo Medina Guzman\n");
                fout.write("Tanya Lizeth Medina Ronquillo\n");
                fout.write("Luis German Mejia Borja Mendez\n");
                fout.write("Jose Leonel Melchor Ceballos\n");
                fout.write("Pedro Angel Mendez Alvarado\n");
                fout.write("Jorge Mendoza Hernandez\n");
                fout.write("Edgar Eduardo Mendoza Velazquez\n");
                fout.write("Dulce Carolina Minor Avila\n");
                fout.write("Hector Minor Velazquez\n");
                fout.write("Enrique Miranda Flores\n");
                fout.write("Hugo Molina Martinez\n");
                fout.write("Oscar Humberto Monjaras Enriquez\n");
                fout.write("Michel Yadira Montelongo Flores\n");
                fout.write("Jose Carlos Montero De Anda\n");
                fout.write("Luis Carlos Montero Leon\n");
                fout.write("Jose Mora Ruacho\n");
                fout.write("Luis Enrique Morales Gutierrez\n");
                fout.write("Hermes Moreno Alvarez\n");
                fout.write("Alicia Sagrario Moreno Arvizo\n");
                fout.write("Olga Teresa Moriel Acosta\n");
                fout.write("Luis Hebbel Moriel Maldonado\n");
                fout.write("Manuel Antolin Morita Ugarte\n");
                fout.write("Pedro Alberto Muela Molina\n");
                fout.write("Eric Alejandro Muller Garcia\n");
                fout.write("Alejandro Muro Hernandez\n");
                fout.write("Gabriela Muñiz Chavez\n");
                fout.write("Ana Yahaira Muños Gamboa\n");
                fout.write("Jesus Manuel Muñoz Languero\n");
                fout.write("Marisa Isabel Muñoz Ochoa\n");
                fout.write("Claudia Georgina Nava Dino\n");
                fout.write("Carmen Julia Navarro Gomez\n");
                fout.write("Erik Alberto Ochoa Corona\n");
                fout.write("Alan Orlando Ochoa Renteria\n");
                fout.write("Jorge Enrique Ochoa Torres\n");
                fout.write("Marcos Gabriel Ogaz Gonzalez\n");
                fout.write("Cecilia Olivia Olague Caballero\n");
                fout.write("Rosa Imelda Olague Caballero\n");
                fout.write("Hugo Alfredo Olivas Acosta\n");
                fout.write("Alejandra Olivas Davila\n");
                fout.write("Olga Cecilia Olivas Rivera\n");
                fout.write("Mario Alberto Olmos Marquez\n");
                fout.write("Alberto Ornelas Hernandez\n");
                fout.write("Alfredo Ornelas Hernandez\n");
                fout.write("Alicia Ornelas Vargas\n");
                fout.write("Adrian Isaac Orpinel Ureta\n");
                fout.write("Patricia Guadalupe Orpinel Ureta\n");
                fout.write("Ricardo Ortega Diaz\n");
                fout.write("Hermila Ortega Mendoza\n");
                fout.write("Linda Carolina Ortega Robles\n");
                fout.write("Eduardo Ortiz Natividad\n");
                fout.write("Abundio Osuna Vizcarra\n");
                fout.write("Angelica Oviedo Garcia\n");
                fout.write("Rafael Edipo Palma Castillo\n");
                fout.write("Pamela Sisi Paredes Araiza\n");
                fout.write("Sergio Arturo Payan Gomez\n");
                fout.write("Velia Perez Gonzalez\n");
                fout.write("Oscar Daniel Perez Piñon\n");
                fout.write("Gerardo Perez Reveles\n");
                fout.write("Miriam Zulemy Perez Rodallegas\n");
                fout.write("Adan Pinales Munguia\n");
                fout.write("Jesus Roberto Pizarro Chavez\n");
                fout.write("Irma Liz Piñon Carmona\n");
                fout.write("Refugio Antonio Piñon Carmona\n");
                fout.write("Nahim Josafat Ponce Lucero\n");
                fout.write("Jose Antonio Portillo Oceguera\n");
                fout.write("Yessica Prieto Maldonado\n");
                fout.write("Olanda Prieto Ordaz\n");
                fout.write("Alberto Quintana Dominguez\n");
                fout.write("Cristina Idalia Quintana Silveira\n");
                fout.write("Erick Octavio Quiones Rodriguez\n");
                fout.write("Luis Carlos Quiñones Baca\n");
                fout.write("Edna Guadalupe Radovich Perez\n");
                fout.write("Francisco Ramirez Kohler\n");
                fout.write("Rocio Alejandra Ramirez Lira\n");
                fout.write("Luis Antonio Ramirez Martinez\n");
                fout.write("Gabriela Rascon Soto\n");
                fout.write("Julia Liliana Requeña Yañez\n");
                fout.write("Ignacio Alfonso Reyes Cortes\n");
                fout.write("Carmen Rosalia Reyes Reyna\n");
                fout.write("Manuel de Jesus Rincon Camacho\n");
                fout.write("Abril Cecilia Rios Lopez\n");
                fout.write("Aurora Robledo Ruiz\n");
                fout.write("Valentin Federico Rodriguez Alvarado\n");
                fout.write("Ricardo Alberto Rodriguez Fonseca\n");
                fout.write("Amparo Margarita Rodriguez Gallegos\n");
                fout.write("Carlos Fransisco Rodriguez Guevara\n");
                fout.write("Beatriz Adriana Rodriguez Varela\n");
                fout.write("Hector David Romero Granados\n");
                fout.write("Jorge Armando Rubio Perea\n");
                fout.write("Adriana Ruiz Anchondo\n");
                fout.write("Hector David Ruiz Cisneros\n");
                fout.write("Yesica Olivia Ruiz Holguin\n");
                fout.write("Jorge Iden Ruiz Quintana\n");
                fout.write("Maria Selene Ruiz Rivero\n");
                fout.write("Rodrigo Ruiz Santos\n");
                fout.write("Oscar Ramses Ruiz Varela\n");
                fout.write("Alfonso Saens Marquez\n");
                fout.write("Jesus Saenz Olivas\n");
                fout.write("Victor Alfonso Salas Aguilar\n");
                fout.write("Lizbeth Salas Lechuga\n");
                fout.write("Luis Alfonso Salcido Hernandez\n");
                fout.write("Saul Alejandro Salomon Jaramillo\n");
                fout.write("Hugo Alejandro San Martin Benavides\n");
                fout.write("Marco Antonio Sanchez Vazquez\n");
                fout.write("Raul Sandoval Jabalera\n");
                fout.write("Laura Veronica Sandoval Romero\n");
                fout.write("Ivonne Aracely Santillan Martinez\n");
                fout.write("Jose Santos Garcia\n");
                fout.write("Daniel Sayto Corona\n");
                fout.write("David Armando Sias Casas\n");
                fout.write("Leonardo Sias Elizondo\n");
                fout.write("Humberto Silva Hidalgo\n");
                fout.write("Claudia Maria Sinaloa Rodriguez\n");
                fout.write("Sergio Solis Castillo\n");
                fout.write("Gilberto Sosa Najera\n");
                fout.write("Erick Ivan Teran Corral\n");
                fout.write("Carlos Alberto Terrazs Venegas\n");
                fout.write("Agustin Javier Tonche Ramos\n");
                fout.write("Daniel Oviel Torres Cisneros\n");
                fout.write("Aaron Torres Orozco\n");
                fout.write("Joaquin Gilberto Treviño Davila\n");
                fout.write("Edgar Trujillo Preciado\n");
                fout.write("Gerardo Trujillo Schiaffino\n");
                fout.write("Maria Ugarte De la Rosa\n");
                fout.write("Wenceslado Melecio Urbina Chavez\n");
                fout.write("Adolfo Valdes Chavez\n");
                fout.write("Carlos Valdez Fragoso\n");
                fout.write("Julio Cesar Valdez Muñoz\n");
                fout.write("Erick Saul Varela Hernandez\n");
                fout.write("Beatriz Vazquez Gonzalez\n");
                fout.write("Maria Isabel Vazquez Gonzalez\n");
                fout.write("Mayra Elena Vega Carrasco\n");
                fout.write("LizzetVelazquez Vega Portillo\n");
                fout.write("Maria Alejandra Velazquez Cazares\n");
                fout.write("Roberto Velazquez Talamantes\n");
                fout.write("Jose Elias Villa Herrera\n");
                fout.write("Marisol Villa Herrera\n");
                fout.write("Maria de Lourdes - Villalba\n");
                fout.write("Alejandro Villalobos Aragon\n");
                fout.close();






            } catch (Exception ex) {

            }
        }


        Intent i = new Intent(this, MainActivity3.class );
        startActivity(i);



    }

    private boolean existe(String[] archivos, String archbusca) {
        for (int f = 0; f < archivos.length; f++)
            if (archbusca.equals(archivos[f]))
                return true;
        return false;
    }


}
